apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bsl-data-pvc
  namespace: bakerst
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
